{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='apiVersion', url='', help='"APIVersion defines a version of an API."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of APIVersion', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'hub.traefik.io/v1alpha1',
    kind: 'APIVersion',
  } + self.metadata.withName(name=name),
  '#spec':: d.obj(help='"The desired behavior of this APIVersion."'),
  spec: {
    '#cors':: d.obj(help='"Cors defines the Cross-Origin Resource Sharing configuration."'),
    cors: {
      '#withAddVaryHeader':: d.fn(help='"AddVaryHeader defines whether the Vary header is automatically added/updated when the AllowOriginsList is set."', args=[d.arg(name='addVaryHeader', type=d.T.boolean)]),
      withAddVaryHeader(addVaryHeader): { spec+: { cors+: { addVaryHeader: addVaryHeader } } },
      '#withAllowCredentials':: d.fn(help='"AllowCredentials defines whether the request can include user credentials."', args=[d.arg(name='allowCredentials', type=d.T.boolean)]),
      withAllowCredentials(allowCredentials): { spec+: { cors+: { allowCredentials: allowCredentials } } },
      '#withAllowHeadersList':: d.fn(help='"AllowHeadersList defines the Access-Control-Request-Headers values sent in preflight response."', args=[d.arg(name='allowHeadersList', type=d.T.array)]),
      withAllowHeadersList(allowHeadersList): { spec+: { cors+: { allowHeadersList: if std.isArray(v=allowHeadersList) then allowHeadersList else [allowHeadersList] } } },
      '#withAllowHeadersListMixin':: d.fn(help='"AllowHeadersList defines the Access-Control-Request-Headers values sent in preflight response."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowHeadersList', type=d.T.array)]),
      withAllowHeadersListMixin(allowHeadersList): { spec+: { cors+: { allowHeadersList+: if std.isArray(v=allowHeadersList) then allowHeadersList else [allowHeadersList] } } },
      '#withAllowMethodsList':: d.fn(help='"AllowMethodsList defines the Access-Control-Request-Method values sent in preflight response."', args=[d.arg(name='allowMethodsList', type=d.T.array)]),
      withAllowMethodsList(allowMethodsList): { spec+: { cors+: { allowMethodsList: if std.isArray(v=allowMethodsList) then allowMethodsList else [allowMethodsList] } } },
      '#withAllowMethodsListMixin':: d.fn(help='"AllowMethodsList defines the Access-Control-Request-Method values sent in preflight response."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowMethodsList', type=d.T.array)]),
      withAllowMethodsListMixin(allowMethodsList): { spec+: { cors+: { allowMethodsList+: if std.isArray(v=allowMethodsList) then allowMethodsList else [allowMethodsList] } } },
      '#withAllowOriginListRegex':: d.fn(help='"AllowOriginListRegex is a list of allowable origins written following the Regular Expression syntax (https://golang.org/pkg/regexp/)."', args=[d.arg(name='allowOriginListRegex', type=d.T.array)]),
      withAllowOriginListRegex(allowOriginListRegex): { spec+: { cors+: { allowOriginListRegex: if std.isArray(v=allowOriginListRegex) then allowOriginListRegex else [allowOriginListRegex] } } },
      '#withAllowOriginListRegexMixin':: d.fn(help='"AllowOriginListRegex is a list of allowable origins written following the Regular Expression syntax (https://golang.org/pkg/regexp/)."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowOriginListRegex', type=d.T.array)]),
      withAllowOriginListRegexMixin(allowOriginListRegex): { spec+: { cors+: { allowOriginListRegex+: if std.isArray(v=allowOriginListRegex) then allowOriginListRegex else [allowOriginListRegex] } } },
      '#withAllowOriginsList':: d.fn(help='"AllowOriginsList is a list of allowable origins. Can also be a wildcard origin \\"*\\"."', args=[d.arg(name='allowOriginsList', type=d.T.array)]),
      withAllowOriginsList(allowOriginsList): { spec+: { cors+: { allowOriginsList: if std.isArray(v=allowOriginsList) then allowOriginsList else [allowOriginsList] } } },
      '#withAllowOriginsListMixin':: d.fn(help='"AllowOriginsList is a list of allowable origins. Can also be a wildcard origin \\"*\\"."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='allowOriginsList', type=d.T.array)]),
      withAllowOriginsListMixin(allowOriginsList): { spec+: { cors+: { allowOriginsList+: if std.isArray(v=allowOriginsList) then allowOriginsList else [allowOriginsList] } } },
      '#withExposeHeadersList':: d.fn(help='"ExposeHeadersList defines the Access-Control-Expose-Headers values sent in preflight response."', args=[d.arg(name='exposeHeadersList', type=d.T.array)]),
      withExposeHeadersList(exposeHeadersList): { spec+: { cors+: { exposeHeadersList: if std.isArray(v=exposeHeadersList) then exposeHeadersList else [exposeHeadersList] } } },
      '#withExposeHeadersListMixin':: d.fn(help='"ExposeHeadersList defines the Access-Control-Expose-Headers values sent in preflight response."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='exposeHeadersList', type=d.T.array)]),
      withExposeHeadersListMixin(exposeHeadersList): { spec+: { cors+: { exposeHeadersList+: if std.isArray(v=exposeHeadersList) then exposeHeadersList else [exposeHeadersList] } } },
      '#withMaxAge':: d.fn(help='"MaxAge defines the time that a preflight request may be cached."', args=[d.arg(name='maxAge', type=d.T.integer)]),
      withMaxAge(maxAge): { spec+: { cors+: { maxAge: maxAge } } },
    },
    '#openApiSpec':: d.obj(help='"OpenAPISpec defines the API contract as an OpenAPI specification."'),
    openApiSpec: {
      '#operationSets':: d.obj(help='"OperationSets defines the sets of operations to be referenced for granular filtering in APICatalogItems or ManagedSubscriptions."'),
      operationSets: {
        '#matchers':: d.obj(help='"Matchers defines a list of alternative rules for matching OpenAPI operations."'),
        matchers: {
          '#withMethods':: d.fn(help='"Methods specifies the HTTP methods to be included for selection."', args=[d.arg(name='methods', type=d.T.array)]),
          withMethods(methods): { methods: if std.isArray(v=methods) then methods else [methods] },
          '#withMethodsMixin':: d.fn(help='"Methods specifies the HTTP methods to be included for selection."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='methods', type=d.T.array)]),
          withMethodsMixin(methods): { methods+: if std.isArray(v=methods) then methods else [methods] },
          '#withPath':: d.fn(help='"Path specifies the exact path of the operations to select."', args=[d.arg(name='path', type=d.T.string)]),
          withPath(path): { path: path },
          '#withPathPrefix':: d.fn(help='"PathPrefix specifies the path prefix of the operations to select."', args=[d.arg(name='pathPrefix', type=d.T.string)]),
          withPathPrefix(pathPrefix): { pathPrefix: pathPrefix },
          '#withPathRegex':: d.fn(help='"PathRegex specifies a regular expression pattern for matching operations based on their paths."', args=[d.arg(name='pathRegex', type=d.T.string)]),
          withPathRegex(pathRegex): { pathRegex: pathRegex },
        },
        '#withMatchers':: d.fn(help='"Matchers defines a list of alternative rules for matching OpenAPI operations."', args=[d.arg(name='matchers', type=d.T.array)]),
        withMatchers(matchers): { matchers: if std.isArray(v=matchers) then matchers else [matchers] },
        '#withMatchersMixin':: d.fn(help='"Matchers defines a list of alternative rules for matching OpenAPI operations."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='matchers', type=d.T.array)]),
        withMatchersMixin(matchers): { matchers+: if std.isArray(v=matchers) then matchers else [matchers] },
        '#withName':: d.fn(help='"Name is the name of the OperationSet to reference in APICatalogItems or ManagedSubscriptions."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { name: name },
      },
      '#override':: d.obj(help='"Override holds data used to override OpenAPI specification."'),
      override: {
        '#servers':: d.obj(help=''),
        servers: {
          '#withUrl':: d.fn(help='', args=[d.arg(name='url', type=d.T.string)]),
          withUrl(url): { url: url },
        },
        '#withServers':: d.fn(help='', args=[d.arg(name='servers', type=d.T.array)]),
        withServers(servers): { spec+: { openApiSpec+: { override+: { servers: if std.isArray(v=servers) then servers else [servers] } } } },
        '#withServersMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='servers', type=d.T.array)]),
        withServersMixin(servers): { spec+: { openApiSpec+: { override+: { servers+: if std.isArray(v=servers) then servers else [servers] } } } },
      },
      '#withOperationSets':: d.fn(help='"OperationSets defines the sets of operations to be referenced for granular filtering in APICatalogItems or ManagedSubscriptions."', args=[d.arg(name='operationSets', type=d.T.array)]),
      withOperationSets(operationSets): { spec+: { openApiSpec+: { operationSets: if std.isArray(v=operationSets) then operationSets else [operationSets] } } },
      '#withOperationSetsMixin':: d.fn(help='"OperationSets defines the sets of operations to be referenced for granular filtering in APICatalogItems or ManagedSubscriptions."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='operationSets', type=d.T.array)]),
      withOperationSetsMixin(operationSets): { spec+: { openApiSpec+: { operationSets+: if std.isArray(v=operationSets) then operationSets else [operationSets] } } },
      '#withPath':: d.fn(help="\"Path specifies the endpoint path within the Kubernetes Service where the OpenAPI specification can be obtained.\\nThe Service queried is determined by the associated Ingress, IngressRoute, or HTTPRoute resource to which the API is attached.\\nIt's important to note that this option is incompatible if the Ingress or IngressRoute specifies multiple backend services.\\nThe Path must be accessible via a GET request method and should serve a YAML or JSON document containing the OpenAPI specification.\"", args=[d.arg(name='path', type=d.T.string)]),
      withPath(path): { spec+: { openApiSpec+: { path: path } } },
      '#withUrl':: d.fn(help='"URL is a Traefik Hub agent accessible URL for obtaining the OpenAPI specification.\\nThe URL must be accessible via a GET request method and should serve a YAML or JSON document containing the OpenAPI specification."', args=[d.arg(name='url', type=d.T.string)]),
      withUrl(url): { spec+: { openApiSpec+: { url: url } } },
      '#withValidateRequestMethodAndPath':: d.fn(help='"ValidateRequestMethodAndPath validates that the path and method matches an operation defined in the OpenAPI specification.\\nThis option overrides the default behavior configured in the static configuration."', args=[d.arg(name='validateRequestMethodAndPath', type=d.T.boolean)]),
      withValidateRequestMethodAndPath(validateRequestMethodAndPath): { spec+: { openApiSpec+: { validateRequestMethodAndPath: validateRequestMethodAndPath } } },
    },
    '#withDescription':: d.fn(help='"Description explains what the APIVersion does."', args=[d.arg(name='description', type=d.T.string)]),
    withDescription(description): { spec+: { description: description } },
    '#withRelease':: d.fn(help='"Release is the version number of the API.\\nThis value must follow the SemVer format: https://semver.org/"', args=[d.arg(name='release', type=d.T.string)]),
    withRelease(release): { spec+: { release: release } },
    '#withTitle':: d.fn(help='"Title is the public facing name of the APIVersion."', args=[d.arg(name='title', type=d.T.string)]),
    withTitle(title): { spec+: { title: title } },
  },
  '#mixin': 'ignore',
  mixin: self,
}
