{
  local d = (import 'doc-util/main.libsonnet'),
  '#':: d.pkg(name='accessControlPolicy', url='', help='"AccessControlPolicy defines an access control policy."'),
  '#metadata':: d.obj(help='"ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create."'),
  metadata: {
    '#withAnnotations':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotations(annotations): { metadata+: { annotations: annotations } },
    '#withAnnotationsMixin':: d.fn(help='"Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata. They are not queryable and should be preserved when modifying objects. More info: http://kubernetes.io/docs/user-guide/annotations"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='annotations', type=d.T.object)]),
    withAnnotationsMixin(annotations): { metadata+: { annotations+: annotations } },
    '#withClusterName':: d.fn(help='"The name of the cluster which the object belongs to. This is used to distinguish resources with same name and namespace in different clusters. This field is not set anywhere right now and apiserver is going to ignore it if set in create or update request."', args=[d.arg(name='clusterName', type=d.T.string)]),
    withClusterName(clusterName): { metadata+: { clusterName: clusterName } },
    '#withCreationTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='creationTimestamp', type=d.T.string)]),
    withCreationTimestamp(creationTimestamp): { metadata+: { creationTimestamp: creationTimestamp } },
    '#withDeletionGracePeriodSeconds':: d.fn(help='"Number of seconds allowed for this object to gracefully terminate before it will be removed from the system. Only set when deletionTimestamp is also set. May only be shortened. Read-only."', args=[d.arg(name='deletionGracePeriodSeconds', type=d.T.integer)]),
    withDeletionGracePeriodSeconds(deletionGracePeriodSeconds): { metadata+: { deletionGracePeriodSeconds: deletionGracePeriodSeconds } },
    '#withDeletionTimestamp':: d.fn(help='"Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers."', args=[d.arg(name='deletionTimestamp', type=d.T.string)]),
    withDeletionTimestamp(deletionTimestamp): { metadata+: { deletionTimestamp: deletionTimestamp } },
    '#withFinalizers':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizers(finalizers): { metadata+: { finalizers: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withFinalizersMixin':: d.fn(help='"Must be empty before the object is deleted from the registry. Each entry is an identifier for the responsible component that will remove the entry from the list. If the deletionTimestamp of the object is non-nil, entries in this list can only be removed. Finalizers may be processed and removed in any order.  Order is NOT enforced because it introduces significant risk of stuck finalizers. finalizers is a shared field, any actor with permission can reorder it. If the finalizer list is processed in order, then this can lead to a situation in which the component responsible for the first finalizer in the list is waiting for a signal (field value, external system, or other) produced by a component responsible for a finalizer later in the list, resulting in a deadlock. Without enforced ordering finalizers are free to order amongst themselves and are not vulnerable to ordering changes in the list."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='finalizers', type=d.T.array)]),
    withFinalizersMixin(finalizers): { metadata+: { finalizers+: if std.isArray(v=finalizers) then finalizers else [finalizers] } },
    '#withGenerateName':: d.fn(help='"GenerateName is an optional prefix, used by the server, to generate a unique name ONLY IF the Name field has not been provided. If this field is used, the name returned to the client will be different than the name passed. This value will also be combined with a unique suffix. The provided value has the same validation rules as the Name field, and may be truncated by the length of the suffix required to make the value unique on the server.\\n\\nIf this field is specified and the generated name exists, the server will NOT return a 409 - instead, it will either return 201 Created or 500 with Reason ServerTimeout indicating a unique name could not be found in the time allotted, and the client should retry (optionally after the time indicated in the Retry-After header).\\n\\nApplied only if Name is not specified. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#idempotency"', args=[d.arg(name='generateName', type=d.T.string)]),
    withGenerateName(generateName): { metadata+: { generateName: generateName } },
    '#withGeneration':: d.fn(help='"A sequence number representing a specific generation of the desired state. Populated by the system. Read-only."', args=[d.arg(name='generation', type=d.T.integer)]),
    withGeneration(generation): { metadata+: { generation: generation } },
    '#withLabels':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"', args=[d.arg(name='labels', type=d.T.object)]),
    withLabels(labels): { metadata+: { labels: labels } },
    '#withLabelsMixin':: d.fn(help='"Map of string keys and values that can be used to organize and categorize (scope and select) objects. May match selectors of replication controllers and services. More info: http://kubernetes.io/docs/user-guide/labels"\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='labels', type=d.T.object)]),
    withLabelsMixin(labels): { metadata+: { labels+: labels } },
    '#withName':: d.fn(help='"Name must be unique within a namespace. Is required when creating resources, although some resources may allow a client to request the generation of an appropriate name automatically. Name is primarily intended for creation idempotence and configuration definition. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/identifiers#names"', args=[d.arg(name='name', type=d.T.string)]),
    withName(name): { metadata+: { name: name } },
    '#withNamespace':: d.fn(help='"Namespace defines the space within which each name must be unique. An empty namespace is equivalent to the \\"default\\" namespace, but \\"default\\" is the canonical representation. Not all objects are required to be scoped to a namespace - the value of this field for those objects will be empty.\\n\\nMust be a DNS_LABEL. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/namespaces"', args=[d.arg(name='namespace', type=d.T.string)]),
    withNamespace(namespace): { metadata+: { namespace: namespace } },
    '#withOwnerReferences':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferences(ownerReferences): { metadata+: { ownerReferences: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withOwnerReferencesMixin':: d.fn(help='"List of objects depended by this object. If ALL objects in the list have been deleted, this object will be garbage collected. If this object is managed by a controller, then an entry in this list will point to this controller, with the controller field set to true. There cannot be more than one managing controller."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='ownerReferences', type=d.T.array)]),
    withOwnerReferencesMixin(ownerReferences): { metadata+: { ownerReferences+: if std.isArray(v=ownerReferences) then ownerReferences else [ownerReferences] } },
    '#withResourceVersion':: d.fn(help='"An opaque value that represents the internal version of this object that can be used by clients to determine when objects have changed. May be used for optimistic concurrency, change detection, and the watch operation on a resource or set of resources. Clients must treat these values as opaque and passed unmodified back to the server. They may only be valid for a particular resource or set of resources.\\n\\nPopulated by the system. Read-only. Value must be treated as opaque by clients and . More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#concurrency-control-and-consistency"', args=[d.arg(name='resourceVersion', type=d.T.string)]),
    withResourceVersion(resourceVersion): { metadata+: { resourceVersion: resourceVersion } },
    '#withSelfLink':: d.fn(help='"SelfLink is a URL representing this object. Populated by the system. Read-only.\\n\\nDEPRECATED Kubernetes will stop propagating this field in 1.20 release and the field is planned to be removed in 1.21 release."', args=[d.arg(name='selfLink', type=d.T.string)]),
    withSelfLink(selfLink): { metadata+: { selfLink: selfLink } },
    '#withUid':: d.fn(help='"UID is the unique in time and space value for this object. It is typically generated by the server on successful creation of a resource and is not allowed to change on PUT operations.\\n\\nPopulated by the system. Read-only. More info: http://kubernetes.io/docs/user-guide/identifiers#uids"', args=[d.arg(name='uid', type=d.T.string)]),
    withUid(uid): { metadata+: { uid: uid } },
  },
  '#new':: d.fn(help='new returns an instance of AccessControlPolicy', args=[d.arg(name='name', type=d.T.string)]),
  new(name): {
    apiVersion: 'hub.traefik.io/v1alpha1',
    kind: 'AccessControlPolicy',
  } + self.metadata.withName(name=name) + self.metadata.withAnnotations(annotations={
    'tanka.dev/namespaced': 'false',
  }),
  '#spec':: d.obj(help='"AccessControlPolicySpec configures an access control policy."'),
  spec: {
    '#apiKey':: d.obj(help='"AccessControlPolicyAPIKey configure an APIKey control policy."'),
    apiKey: {
      '#keySource':: d.obj(help='"KeySource defines how to extract API keys from requests."'),
      keySource: {
        '#withCookie':: d.fn(help='"Cookie is the name of a cookie."', args=[d.arg(name='cookie', type=d.T.string)]),
        withCookie(cookie): { spec+: { apiKey+: { keySource+: { cookie: cookie } } } },
        '#withHeader':: d.fn(help='"Header is the name of a header."', args=[d.arg(name='header', type=d.T.string)]),
        withHeader(header): { spec+: { apiKey+: { keySource+: { header: header } } } },
        '#withHeaderAuthScheme':: d.fn(help='"HeaderAuthScheme sets an optional auth scheme when Header is set to \\"Authorization\\".\\nIf set, this scheme is removed from the token, and all requests not including it are dropped."', args=[d.arg(name='headerAuthScheme', type=d.T.string)]),
        withHeaderAuthScheme(headerAuthScheme): { spec+: { apiKey+: { keySource+: { headerAuthScheme: headerAuthScheme } } } },
        '#withQuery':: d.fn(help='"Query is the name of a query parameter."', args=[d.arg(name='query', type=d.T.string)]),
        withQuery(query): { spec+: { apiKey+: { keySource+: { query: query } } } },
      },
      '#keys':: d.obj(help='"Keys define the set of authorized keys to access a protected resource."'),
      keys: {
        '#withId':: d.fn(help='"ID is the unique identifier of the key."', args=[d.arg(name='id', type=d.T.string)]),
        withId(id): { id: id },
        '#withMetadata':: d.fn(help='"Metadata holds arbitrary metadata for this key, can be used by ForwardHeaders."', args=[d.arg(name='metadata', type=d.T.object)]),
        withMetadata(metadata): { metadata: metadata },
        '#withMetadataMixin':: d.fn(help='"Metadata holds arbitrary metadata for this key, can be used by ForwardHeaders."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='metadata', type=d.T.object)]),
        withMetadataMixin(metadata): { metadata+: metadata },
        '#withValue':: d.fn(help='"Value is the SHAKE-256 hash (using 64 bytes) of the API key."', args=[d.arg(name='value', type=d.T.string)]),
        withValue(value): { value: value },
      },
      '#withForwardHeaders':: d.fn(help='"ForwardHeaders instructs the middleware to forward key metadata as header values upon successful authentication."', args=[d.arg(name='forwardHeaders', type=d.T.object)]),
      withForwardHeaders(forwardHeaders): { spec+: { apiKey+: { forwardHeaders: forwardHeaders } } },
      '#withForwardHeadersMixin':: d.fn(help='"ForwardHeaders instructs the middleware to forward key metadata as header values upon successful authentication."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='forwardHeaders', type=d.T.object)]),
      withForwardHeadersMixin(forwardHeaders): { spec+: { apiKey+: { forwardHeaders+: forwardHeaders } } },
      '#withKeys':: d.fn(help='"Keys define the set of authorized keys to access a protected resource."', args=[d.arg(name='keys', type=d.T.array)]),
      withKeys(keys): { spec+: { apiKey+: { keys: if std.isArray(v=keys) then keys else [keys] } } },
      '#withKeysMixin':: d.fn(help='"Keys define the set of authorized keys to access a protected resource."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='keys', type=d.T.array)]),
      withKeysMixin(keys): { spec+: { apiKey+: { keys+: if std.isArray(v=keys) then keys else [keys] } } },
    },
    '#basicAuth':: d.obj(help='"AccessControlPolicyBasicAuth holds the HTTP basic authentication configuration."'),
    basicAuth: {
      '#withForwardUsernameHeader':: d.fn(help='', args=[d.arg(name='forwardUsernameHeader', type=d.T.string)]),
      withForwardUsernameHeader(forwardUsernameHeader): { spec+: { basicAuth+: { forwardUsernameHeader: forwardUsernameHeader } } },
      '#withRealm':: d.fn(help='', args=[d.arg(name='realm', type=d.T.string)]),
      withRealm(realm): { spec+: { basicAuth+: { realm: realm } } },
      '#withStripAuthorizationHeader':: d.fn(help='', args=[d.arg(name='stripAuthorizationHeader', type=d.T.boolean)]),
      withStripAuthorizationHeader(stripAuthorizationHeader): { spec+: { basicAuth+: { stripAuthorizationHeader: stripAuthorizationHeader } } },
      '#withUsers':: d.fn(help='', args=[d.arg(name='users', type=d.T.array)]),
      withUsers(users): { spec+: { basicAuth+: { users: if std.isArray(v=users) then users else [users] } } },
      '#withUsersMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='users', type=d.T.array)]),
      withUsersMixin(users): { spec+: { basicAuth+: { users+: if std.isArray(v=users) then users else [users] } } },
    },
    '#jwt':: d.obj(help='"AccessControlPolicyJWT configures a JWT access control policy."'),
    jwt: {
      '#withClaims':: d.fn(help='', args=[d.arg(name='claims', type=d.T.string)]),
      withClaims(claims): { spec+: { jwt+: { claims: claims } } },
      '#withForwardHeaders':: d.fn(help='', args=[d.arg(name='forwardHeaders', type=d.T.object)]),
      withForwardHeaders(forwardHeaders): { spec+: { jwt+: { forwardHeaders: forwardHeaders } } },
      '#withForwardHeadersMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='forwardHeaders', type=d.T.object)]),
      withForwardHeadersMixin(forwardHeaders): { spec+: { jwt+: { forwardHeaders+: forwardHeaders } } },
      '#withJwksFile':: d.fn(help='', args=[d.arg(name='jwksFile', type=d.T.string)]),
      withJwksFile(jwksFile): { spec+: { jwt+: { jwksFile: jwksFile } } },
      '#withJwksUrl':: d.fn(help='', args=[d.arg(name='jwksUrl', type=d.T.string)]),
      withJwksUrl(jwksUrl): { spec+: { jwt+: { jwksUrl: jwksUrl } } },
      '#withPublicKey':: d.fn(help='', args=[d.arg(name='publicKey', type=d.T.string)]),
      withPublicKey(publicKey): { spec+: { jwt+: { publicKey: publicKey } } },
      '#withSigningSecret':: d.fn(help='', args=[d.arg(name='signingSecret', type=d.T.string)]),
      withSigningSecret(signingSecret): { spec+: { jwt+: { signingSecret: signingSecret } } },
      '#withSigningSecretBase64Encoded':: d.fn(help='', args=[d.arg(name='signingSecretBase64Encoded', type=d.T.boolean)]),
      withSigningSecretBase64Encoded(signingSecretBase64Encoded): { spec+: { jwt+: { signingSecretBase64Encoded: signingSecretBase64Encoded } } },
      '#withStripAuthorizationHeader':: d.fn(help='', args=[d.arg(name='stripAuthorizationHeader', type=d.T.boolean)]),
      withStripAuthorizationHeader(stripAuthorizationHeader): { spec+: { jwt+: { stripAuthorizationHeader: stripAuthorizationHeader } } },
      '#withTokenQueryKey':: d.fn(help='', args=[d.arg(name='tokenQueryKey', type=d.T.string)]),
      withTokenQueryKey(tokenQueryKey): { spec+: { jwt+: { tokenQueryKey: tokenQueryKey } } },
    },
    '#oAuthIntro':: d.obj(help='"AccessControlOAuthIntro configures an OAuth 2.0 Token Introspection access control policy."'),
    oAuthIntro: {
      '#clientConfig':: d.obj(help='"AccessControlOAuthIntroClientConfig configures the OAuth 2.0 client for issuing token introspection requests."'),
      clientConfig: {
        '#tls':: d.obj(help='"TLS configures TLS communication with the Authorization Server."'),
        tls: {
          '#withCa':: d.fn(help='"CA sets the CA bundle used to sign the Authorization Server certificate."', args=[d.arg(name='ca', type=d.T.string)]),
          withCa(ca): { spec+: { oAuthIntro+: { clientConfig+: { tls+: { ca: ca } } } } },
          '#withInsecureSkipVerify':: d.fn(help='"InsecureSkipVerify skips the Authorization Server certificate validation.\\nFor testing purposes only, do not use in production."', args=[d.arg(name='insecureSkipVerify', type=d.T.boolean)]),
          withInsecureSkipVerify(insecureSkipVerify): { spec+: { oAuthIntro+: { clientConfig+: { tls+: { insecureSkipVerify: insecureSkipVerify } } } } },
        },
        '#withHeaders':: d.fn(help='"Headers to set when sending requests to the Authorization Server."', args=[d.arg(name='headers', type=d.T.object)]),
        withHeaders(headers): { spec+: { oAuthIntro+: { clientConfig+: { headers: headers } } } },
        '#withHeadersMixin':: d.fn(help='"Headers to set when sending requests to the Authorization Server."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='headers', type=d.T.object)]),
        withHeadersMixin(headers): { spec+: { oAuthIntro+: { clientConfig+: { headers+: headers } } } },
        '#withMaxRetries':: d.fn(help='"MaxRetries defines the number of retries for introspection requests."', args=[d.arg(name='maxRetries', type=d.T.integer)]),
        withMaxRetries(maxRetries): { spec+: { oAuthIntro+: { clientConfig+: { maxRetries: maxRetries } } } },
        '#withTimeoutSeconds':: d.fn(help='"TimeoutSeconds configures the maximum amount of seconds to wait before giving up on requests."', args=[d.arg(name='timeoutSeconds', type=d.T.integer)]),
        withTimeoutSeconds(timeoutSeconds): { spec+: { oAuthIntro+: { clientConfig+: { timeoutSeconds: timeoutSeconds } } } },
        '#withTokenTypeHint':: d.fn(help='"TokenTypeHint is a hint to pass to the Authorization Server.\\nSee https://tools.ietf.org/html/rfc7662#section-2.1 for more information."', args=[d.arg(name='tokenTypeHint', type=d.T.string)]),
        withTokenTypeHint(tokenTypeHint): { spec+: { oAuthIntro+: { clientConfig+: { tokenTypeHint: tokenTypeHint } } } },
        '#withUrl':: d.fn(help='"URL of the Authorization Server."', args=[d.arg(name='url', type=d.T.string)]),
        withUrl(url): { spec+: { oAuthIntro+: { clientConfig+: { url: url } } } },
      },
      '#tokenSource':: d.obj(help='"TokenSource describes how to extract tokens from HTTP requests.\\nIf multiple sources are set, the order is the following: header > query > cookie."'),
      tokenSource: {
        '#withCookie':: d.fn(help='"Cookie is the name of a cookie."', args=[d.arg(name='cookie', type=d.T.string)]),
        withCookie(cookie): { spec+: { oAuthIntro+: { tokenSource+: { cookie: cookie } } } },
        '#withHeader':: d.fn(help='"Header is the name of a header."', args=[d.arg(name='header', type=d.T.string)]),
        withHeader(header): { spec+: { oAuthIntro+: { tokenSource+: { header: header } } } },
        '#withHeaderAuthScheme':: d.fn(help='"HeaderAuthScheme sets an optional auth scheme when Header is set to \\"Authorization\\".\\nIf set, this scheme is removed from the token, and all requests not including it are dropped."', args=[d.arg(name='headerAuthScheme', type=d.T.string)]),
        withHeaderAuthScheme(headerAuthScheme): { spec+: { oAuthIntro+: { tokenSource+: { headerAuthScheme: headerAuthScheme } } } },
        '#withQuery':: d.fn(help='"Query is the name of a query parameter."', args=[d.arg(name='query', type=d.T.string)]),
        withQuery(query): { spec+: { oAuthIntro+: { tokenSource+: { query: query } } } },
      },
      '#withClaims':: d.fn(help='', args=[d.arg(name='claims', type=d.T.string)]),
      withClaims(claims): { spec+: { oAuthIntro+: { claims: claims } } },
      '#withForwardHeaders':: d.fn(help='', args=[d.arg(name='forwardHeaders', type=d.T.object)]),
      withForwardHeaders(forwardHeaders): { spec+: { oAuthIntro+: { forwardHeaders: forwardHeaders } } },
      '#withForwardHeadersMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='forwardHeaders', type=d.T.object)]),
      withForwardHeadersMixin(forwardHeaders): { spec+: { oAuthIntro+: { forwardHeaders+: forwardHeaders } } },
    },
    '#oidc':: d.obj(help='"AccessControlPolicyOIDC holds the OIDC authentication configuration."'),
    oidc: {
      '#secret':: d.obj(help='"SecretReference represents a Secret Reference. It has enough information to retrieve secret\\nin any namespace"'),
      secret: {
        '#withName':: d.fn(help='"name is unique within a namespace to reference a secret resource."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { oidc+: { secret+: { name: name } } } },
        '#withNamespace':: d.fn(help='"namespace defines the space within which the secret name must be unique."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { oidc+: { secret+: { namespace: namespace } } } },
      },
      '#session':: d.obj(help='"Session holds session configuration."'),
      session: {
        '#withDomain':: d.fn(help='', args=[d.arg(name='domain', type=d.T.string)]),
        withDomain(domain): { spec+: { oidc+: { session+: { domain: domain } } } },
        '#withPath':: d.fn(help='', args=[d.arg(name='path', type=d.T.string)]),
        withPath(path): { spec+: { oidc+: { session+: { path: path } } } },
        '#withRefresh':: d.fn(help='', args=[d.arg(name='refresh', type=d.T.boolean)]),
        withRefresh(refresh): { spec+: { oidc+: { session+: { refresh: refresh } } } },
        '#withSameSite':: d.fn(help='', args=[d.arg(name='sameSite', type=d.T.string)]),
        withSameSite(sameSite): { spec+: { oidc+: { session+: { sameSite: sameSite } } } },
        '#withSecure':: d.fn(help='', args=[d.arg(name='secure', type=d.T.boolean)]),
        withSecure(secure): { spec+: { oidc+: { session+: { secure: secure } } } },
      },
      '#stateCookie':: d.obj(help='"StateCookie holds state cookie configuration."'),
      stateCookie: {
        '#withDomain':: d.fn(help='', args=[d.arg(name='domain', type=d.T.string)]),
        withDomain(domain): { spec+: { oidc+: { stateCookie+: { domain: domain } } } },
        '#withPath':: d.fn(help='', args=[d.arg(name='path', type=d.T.string)]),
        withPath(path): { spec+: { oidc+: { stateCookie+: { path: path } } } },
        '#withSameSite':: d.fn(help='', args=[d.arg(name='sameSite', type=d.T.string)]),
        withSameSite(sameSite): { spec+: { oidc+: { stateCookie+: { sameSite: sameSite } } } },
        '#withSecure':: d.fn(help='', args=[d.arg(name='secure', type=d.T.boolean)]),
        withSecure(secure): { spec+: { oidc+: { stateCookie+: { secure: secure } } } },
      },
      '#withAuthParams':: d.fn(help='', args=[d.arg(name='authParams', type=d.T.object)]),
      withAuthParams(authParams): { spec+: { oidc+: { authParams: authParams } } },
      '#withAuthParamsMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='authParams', type=d.T.object)]),
      withAuthParamsMixin(authParams): { spec+: { oidc+: { authParams+: authParams } } },
      '#withClaims':: d.fn(help='', args=[d.arg(name='claims', type=d.T.string)]),
      withClaims(claims): { spec+: { oidc+: { claims: claims } } },
      '#withClientId':: d.fn(help='', args=[d.arg(name='clientId', type=d.T.string)]),
      withClientId(clientId): { spec+: { oidc+: { clientId: clientId } } },
      '#withDisableAuthRedirectionPaths':: d.fn(help='', args=[d.arg(name='disableAuthRedirectionPaths', type=d.T.array)]),
      withDisableAuthRedirectionPaths(disableAuthRedirectionPaths): { spec+: { oidc+: { disableAuthRedirectionPaths: if std.isArray(v=disableAuthRedirectionPaths) then disableAuthRedirectionPaths else [disableAuthRedirectionPaths] } } },
      '#withDisableAuthRedirectionPathsMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='disableAuthRedirectionPaths', type=d.T.array)]),
      withDisableAuthRedirectionPathsMixin(disableAuthRedirectionPaths): { spec+: { oidc+: { disableAuthRedirectionPaths+: if std.isArray(v=disableAuthRedirectionPaths) then disableAuthRedirectionPaths else [disableAuthRedirectionPaths] } } },
      '#withForwardHeaders':: d.fn(help='', args=[d.arg(name='forwardHeaders', type=d.T.object)]),
      withForwardHeaders(forwardHeaders): { spec+: { oidc+: { forwardHeaders: forwardHeaders } } },
      '#withForwardHeadersMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='forwardHeaders', type=d.T.object)]),
      withForwardHeadersMixin(forwardHeaders): { spec+: { oidc+: { forwardHeaders+: forwardHeaders } } },
      '#withIssuer':: d.fn(help='', args=[d.arg(name='issuer', type=d.T.string)]),
      withIssuer(issuer): { spec+: { oidc+: { issuer: issuer } } },
      '#withLogoutUrl':: d.fn(help='', args=[d.arg(name='logoutUrl', type=d.T.string)]),
      withLogoutUrl(logoutUrl): { spec+: { oidc+: { logoutUrl: logoutUrl } } },
      '#withRedirectUrl':: d.fn(help='', args=[d.arg(name='redirectUrl', type=d.T.string)]),
      withRedirectUrl(redirectUrl): { spec+: { oidc+: { redirectUrl: redirectUrl } } },
      '#withScopes':: d.fn(help='', args=[d.arg(name='scopes', type=d.T.array)]),
      withScopes(scopes): { spec+: { oidc+: { scopes: if std.isArray(v=scopes) then scopes else [scopes] } } },
      '#withScopesMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='scopes', type=d.T.array)]),
      withScopesMixin(scopes): { spec+: { oidc+: { scopes+: if std.isArray(v=scopes) then scopes else [scopes] } } },
    },
    '#oidcGoogle':: d.obj(help='"AccessControlPolicyOIDCGoogle holds the Google OIDC authentication configuration."'),
    oidcGoogle: {
      '#secret':: d.obj(help='"SecretReference represents a Secret Reference. It has enough information to retrieve secret\\nin any namespace"'),
      secret: {
        '#withName':: d.fn(help='"name is unique within a namespace to reference a secret resource."', args=[d.arg(name='name', type=d.T.string)]),
        withName(name): { spec+: { oidcGoogle+: { secret+: { name: name } } } },
        '#withNamespace':: d.fn(help='"namespace defines the space within which the secret name must be unique."', args=[d.arg(name='namespace', type=d.T.string)]),
        withNamespace(namespace): { spec+: { oidcGoogle+: { secret+: { namespace: namespace } } } },
      },
      '#session':: d.obj(help='"Session holds session configuration."'),
      session: {
        '#withDomain':: d.fn(help='', args=[d.arg(name='domain', type=d.T.string)]),
        withDomain(domain): { spec+: { oidcGoogle+: { session+: { domain: domain } } } },
        '#withPath':: d.fn(help='', args=[d.arg(name='path', type=d.T.string)]),
        withPath(path): { spec+: { oidcGoogle+: { session+: { path: path } } } },
        '#withRefresh':: d.fn(help='', args=[d.arg(name='refresh', type=d.T.boolean)]),
        withRefresh(refresh): { spec+: { oidcGoogle+: { session+: { refresh: refresh } } } },
        '#withSameSite':: d.fn(help='', args=[d.arg(name='sameSite', type=d.T.string)]),
        withSameSite(sameSite): { spec+: { oidcGoogle+: { session+: { sameSite: sameSite } } } },
        '#withSecure':: d.fn(help='', args=[d.arg(name='secure', type=d.T.boolean)]),
        withSecure(secure): { spec+: { oidcGoogle+: { session+: { secure: secure } } } },
      },
      '#stateCookie':: d.obj(help='"StateCookie holds state cookie configuration."'),
      stateCookie: {
        '#withDomain':: d.fn(help='', args=[d.arg(name='domain', type=d.T.string)]),
        withDomain(domain): { spec+: { oidcGoogle+: { stateCookie+: { domain: domain } } } },
        '#withPath':: d.fn(help='', args=[d.arg(name='path', type=d.T.string)]),
        withPath(path): { spec+: { oidcGoogle+: { stateCookie+: { path: path } } } },
        '#withSameSite':: d.fn(help='', args=[d.arg(name='sameSite', type=d.T.string)]),
        withSameSite(sameSite): { spec+: { oidcGoogle+: { stateCookie+: { sameSite: sameSite } } } },
        '#withSecure':: d.fn(help='', args=[d.arg(name='secure', type=d.T.boolean)]),
        withSecure(secure): { spec+: { oidcGoogle+: { stateCookie+: { secure: secure } } } },
      },
      '#withAuthParams':: d.fn(help='', args=[d.arg(name='authParams', type=d.T.object)]),
      withAuthParams(authParams): { spec+: { oidcGoogle+: { authParams: authParams } } },
      '#withAuthParamsMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='authParams', type=d.T.object)]),
      withAuthParamsMixin(authParams): { spec+: { oidcGoogle+: { authParams+: authParams } } },
      '#withClientId':: d.fn(help='', args=[d.arg(name='clientId', type=d.T.string)]),
      withClientId(clientId): { spec+: { oidcGoogle+: { clientId: clientId } } },
      '#withEmails':: d.fn(help='"Emails are the allowed emails to connect."', args=[d.arg(name='emails', type=d.T.array)]),
      withEmails(emails): { spec+: { oidcGoogle+: { emails: if std.isArray(v=emails) then emails else [emails] } } },
      '#withEmailsMixin':: d.fn(help='"Emails are the allowed emails to connect."\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='emails', type=d.T.array)]),
      withEmailsMixin(emails): { spec+: { oidcGoogle+: { emails+: if std.isArray(v=emails) then emails else [emails] } } },
      '#withForwardHeaders':: d.fn(help='', args=[d.arg(name='forwardHeaders', type=d.T.object)]),
      withForwardHeaders(forwardHeaders): { spec+: { oidcGoogle+: { forwardHeaders: forwardHeaders } } },
      '#withForwardHeadersMixin':: d.fn(help='\n\n**Note:** This function appends passed data to existing values', args=[d.arg(name='forwardHeaders', type=d.T.object)]),
      withForwardHeadersMixin(forwardHeaders): { spec+: { oidcGoogle+: { forwardHeaders+: forwardHeaders } } },
      '#withLogoutUrl':: d.fn(help='', args=[d.arg(name='logoutUrl', type=d.T.string)]),
      withLogoutUrl(logoutUrl): { spec+: { oidcGoogle+: { logoutUrl: logoutUrl } } },
      '#withRedirectUrl':: d.fn(help='', args=[d.arg(name='redirectUrl', type=d.T.string)]),
      withRedirectUrl(redirectUrl): { spec+: { oidcGoogle+: { redirectUrl: redirectUrl } } },
    },
  },
  '#mixin': 'ignore',
  mixin: self,
}
